application: gopherkamil
version: blog-test
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /LICENSE
  static_files: static/LICENSE
  upload: static/LICENSE
  mime_type: text/plain
- url: /.*
  script: _go_app

nobuild_files: ^(support|content)/
